export const modules = [
  {
    id: "help",
    shortCode: "MB-01 MONEY",
    name: "HELP Loan Calculator",
    status: "Live now",
    statusTone: "live",
    accent: "mint",
    image: "/assets/console/mb01-console-help-loaded-v1.webp",
    description: "See how debt, income, indexation and life events could change your payoff path.",
    action: "Launch calculator",
    href: "https://www.helploancalculator.com",
    detail: "Free utility module",
  },
  {
    id: "tuesday-type",
    shortCode: "MB-01 TYPE",
    name: "Tuesday Type",
    status: "In development",
    statusTone: "development",
    accent: "blue",
    image: "/assets/console/mb01-console-tuesday-type-loaded-v1.webp",
    description: "A life-design quiz that helps you decide who you're becoming, not diagnose who you are.",
    detail: "Discovery module",
  },
  {
    id: "big-game",
    shortCode: "MB-01 GAME",
    name: "Big Game Playbook",
    status: "Early concept",
    statusTone: "concept",
    accent: "yellow",
    image: "/assets/console/mb01-console-big-game-playbook-loaded-v1.webp",
    description: "A future planning idea still being discovered. The cartridge is locked. The product is not.",
    detail: "Strategy concept",
  },
  {
    id: "clubhouse",
    shortCode: "MB-01 CLUB",
    name: "The Clubhouse",
    status: "Concept",
    statusTone: "concept",
    accent: "pink",
    image: "/assets/console/mb01-console-clubhouse-loaded-v1.webp",
    description:
      "A future home for tools, community and progress, designed to start with meaning instead of a blank dashboard.",
    detail: "Community concept",
  },
];
