export const modules = [
  {
    id: "dream-life",
    shortCode: "MB-01 LIFE",
    name: "Dream Life Calculator",
    status: "Live now",
    statusTone: "live",
    accent: "purple",
    cartridgeImage: "/assets/cartridges/dream-life-calculator-cartridge-v1.webp",
    image: "/assets/console/mb01-console-dream-life-loaded-v1.webp",
    description: "Build the life you want, price it honestly, then explore the income that could support it.",
    action: "Launch calculator",
    href: "/dream-life-calculator",
    detail: "Free lifestyle module",
  },
  {
    id: "help",
    shortCode: "MB-01 MONEY",
    name: "HECS Debt Calculator",
    status: "Live now",
    statusTone: "live",
    accent: "mint",
    cartridgeImage: "/assets/cartridges/hecs-debt-calculator-cartridge-v1.jpg",
    cartridgeFit: "contain",
    image: "/assets/console/mb01-console-hecs-debt-calculator-loaded-v1.jpg",
    description: "See how debt, income, indexation and life events could change your payoff path.",
    action: "Launch calculator",
    href: "/hecs-debt-calculator",
    detail: "Free utility module",
  },
  {
    id: "tuesday-type",
    shortCode: "MB-01 TYPE",
    name: "Tuesday Type",
    status: "In development",
    statusTone: "development",
    accent: "blue",
    cartridgeImage: "/assets/cartridges/tuesday-type-cartridge-v1.webp",
    image: "/assets/console/mb01-console-tuesday-type-loaded-v1.webp",
    description: "Choose how you want to operate, picture the ordinary life those choices create, then test the direction.",
    detail: "Personal operating module",
  },
  {
    id: "big-game",
    shortCode: "MB-01 GAME",
    name: "Big Game Playbook",
    status: "Early concept",
    statusTone: "concept",
    accent: "yellow",
    cartridgeImage: "/assets/cartridges/big-game-playbook-cartridge-v1.webp",
    image: "/assets/console/mb01-console-big-game-playbook-loaded-v1.webp",
    description: "A future planning idea still being discovered. The cartridge is locked. The product is not.",
    detail: "Strategy concept",
  },
  {
    id: "clubhouse",
    shortCode: "MB-01 CLUB",
    name: "The Clubhouse",
    status: "Concept",
    statusTone: "concept",
    accent: "pink",
    cartridgeImage: "/assets/cartridges/the-clubhouse-cartridge-v1.webp",
    image: "/assets/console/mb01-console-clubhouse-loaded-v1.webp",
    description:
      "A future home for tools, community and progress, designed to start with meaning instead of a blank dashboard.",
    detail: "Community concept",
  },
];
